"use client";

import { memo } from "react";
import {
  Home24Regular,
  Home24Filled,
  Tag24Regular,
  Tag24Filled,
  Cloud24Regular,
  Cloud24Filled,
  Chat24Regular,
  Chat24Filled,
  Megaphone24Regular,
  Megaphone24Filled,
  People24Regular,
  People24Filled,
  Settings24Regular,
  Settings24Filled,
  MoreHorizontal24Regular,
  Dismiss24Regular,
  Send24Regular,
  ArrowLeft24Regular,
  Link24Regular,
  ArrowMinimize24Regular,
  ArrowMaximize24Regular,
  WindowNew24Regular,
  WindowArrowUp24Regular,
  Person24Regular,
  Person24Filled,
  Document24Regular,
  MusicNote124Regular,
  Alert24Regular,
  Globe24Regular,
  Folder24Regular,
  ArrowSync24Regular,
  Board24Regular,
  Circle24Regular,
  PaintBrush24Regular,
  DesktopSpeaker24Regular,
  PlugConnected24Regular,
  WeatherMoon24Filled,
  WeatherSunny24Filled,
  Wand24Regular,
  ArrowDownload24Regular,
  Share24Regular,
  Eye24Regular,
  Copy24Regular,
  Delete24Regular,
  ArrowRepeatAll24Regular,
  Add24Regular,
  Comment24Regular,
  ChevronRight24Regular,
  ArrowSortDown24Regular,
  MailInbox24Regular,
  ArrowRight24Regular,
  Star24Regular,
  Star24Filled,
  QrCode24Regular,
  SportSoccer24Regular,
  Library24Regular,
  Trophy24Regular,
  Question24Regular,
  AppsList24Regular,
  TextBulletList24Regular,
  WeatherDrizzle24Regular,
  WifiOff24Regular,
  ErrorCircle24Filled,
  Play24Regular,
  Pause24Regular,
  DesktopSignal24Regular,
  LayoutDynamic24Regular,
  WindowDevTools24Regular,
  WindowDevTools24Filled,
  CheckmarkCircle24Filled,
  Database24Regular,
  Shield24Regular,
  Key24Regular,
  Flag24Regular,
  Server24Regular,
  History24Regular,
  Emoji24Regular,
  LockClosed24Regular,
  Warning24Regular,
  Info24Regular,
  Search24Regular,
  ArrowUpload24Regular,
  Edit24Regular,
  ViewDesktop24Regular,
  ArrowRight16Regular,
  ArrowEnter16Regular,
  Earth16Filled,
  Timeline20Filled,
  ServerLink20Filled,
  ChartMultiple16Filled,
  type FluentIcon,
} from "@fluentui/react-icons";

const iconMap: Record<string, FluentIcon> = {
  home: Home24Regular,
  home_filled: Home24Filled,
  tag: Tag24Regular,
  tag_filled: Tag24Filled,
  cloud: Cloud24Regular,
  cloud_filled: Cloud24Filled,
  chat: Chat24Regular,
  chat_filled: Chat24Filled,
  campaign: Megaphone24Regular,
  campaign_filled: Megaphone24Filled,
  group: People24Regular,
  group_filled: People24Filled,
  settings: Settings24Regular,
  settings_filled: Settings24Filled,
  more_horiz: MoreHorizontal24Regular,
  close: Dismiss24Regular,
  send: Send24Regular,
  arrow_left: ArrowLeft24Regular,
  link: Link24Regular,
  minimize: ArrowMinimize24Regular,
  maximize: ArrowMaximize24Regular,
  open_in_new: WindowNew24Regular,
  window_arrow_up: WindowArrowUp24Regular,
  person: Person24Regular,
  person_filled: Person24Filled,
  article: Document24Regular,
  music_note: MusicNote124Regular,
  notifications: Alert24Regular,
  public: Globe24Regular,
  globe: Globe24Regular,
  dns: Globe24Regular,
  folder: Folder24Regular,
  folder_shared: Folder24Regular,
  sync: ArrowSync24Regular,
  dashboard: Board24Regular,
  hub: Circle24Regular,
  palette: PaintBrush24Regular,
  volume_up: DesktopSpeaker24Regular,
  extension: PlugConnected24Regular,
  dark_mode: WeatherMoon24Filled,
  light_mode: WeatherSunny24Filled,
  settings_brightness: Settings24Regular,
  wand: Wand24Regular,
  download: ArrowDownload24Regular,
  share: Share24Regular,
  eye: Eye24Regular,
  copy: Copy24Regular,
  delete: Delete24Regular,
  refresh: ArrowSync24Regular,
  chat_bubble: Comment24Regular,
  repeat: ArrowRepeatAll24Regular,
  subdirectory_arrow_right: ArrowRight24Regular,
  add: Add24Regular,
  comment: Comment24Regular,
  chevron_right: ChevronRight24Regular,
  arrow_drop_down: ArrowSortDown24Regular,
  inbox: MailInbox24Regular,
  dynamic_feed: LayoutDynamic24Regular,
  widgets: AppsList24Regular,
  signal_cellular_alt: DesktopSignal24Regular,
  wifi_off: WifiOff24Regular,
  error: ErrorCircle24Filled,
  play_arrow: Play24Regular,
  pause: Pause24Regular,
  star_outline: Star24Regular,
  star: Star24Filled,
  qr_code: QrCode24Regular,
  sports_esports: SportSoccer24Regular,
  photo_library: Library24Regular,
  military_tech: Trophy24Regular,
  help_outline: Question24Regular,
  terminal: WindowDevTools24Regular,
  window_dev_tools_filled: WindowDevTools24Filled,
  check_circle: CheckmarkCircle24Filled,
  text_list: TextBulletList24Regular,
  weather_drizzle: WeatherDrizzle24Regular,
  database: Database24Regular,
  shield: Shield24Regular,
  key: Key24Regular,
  flag: Flag24Regular,
  server: Server24Regular,
  history: History24Regular,
  emoji: Emoji24Regular,
  lock: LockClosed24Regular,
  warning: Warning24Regular,
  info: Info24Regular,
  search: Search24Regular,
  upload: ArrowUpload24Regular,
  edit: Edit24Regular,
  view: ViewDesktop24Regular,
  arrow_right_16: ArrowRight16Regular,
  arrow_enter_16: ArrowEnter16Regular,
  earth_16_filled: Earth16Filled,
  timeline_20_filled: Timeline20Filled,
  server_link_20_filled: ServerLink20Filled,
  chart_multiple_16_filled: ChartMultiple16Filled,
};

interface IconProps {
  name: string;
  className?: string;
  filled?: boolean;
  fontSize?: number | string;
}

export const Icon = memo(function Icon({ name, className = "", filled = false, fontSize }: IconProps) {
  const baseName = name.replace("_filled", "");
  const key = filled ? `${baseName}_filled` : name;
  const IconComponent = iconMap[key] || iconMap[baseName] || iconMap["tag"];

  return (
    <IconComponent
      className={className}
      style={fontSize ? { fontSize, width: "1em", height: "1em" } : undefined}
    />
  );
});
